### ISSUE TITLE
I can not run the project on My pc 

### ISSUE THREAD

**Issue by walid885** [NishanthARao/Python-Quadrotor-Simulation#1]
from render_animation import animate_quad

i always have an issue here , trying  to run this! and even after trying to searche the render_animation , i couldn't find it anywhere? like , what is the issue here or how shall i solve it ?

**Comment by NishanthARao** [comment]
Hey, I just realized that the module `render_animation` is not required here! I have updated the file, and this should run without any errors! Thanks for pointing this out!
